# Generated by Django 6.0.5 on 2026-05-08 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('artist', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('album', models.CharField(blank=True, default='Unknown', max_length=200)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds')),
                ('file_path', models.CharField(max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title', 'artist'], name='music_song_title_a920c3_idx')],
            },
        ),
    ]
